
version: "3"

sevices:
    server:
        build: server/

        ports:
          - 8080:8080

    client:
      build: client/

      ports:
        - 3000:3000

    nginx:
      build: nginx/

      ports:
        - 443:443